[2022/10/11 18:42:39][INFO][][0] 工作路径已切换到 d:\rpa机器人\百纳\
[2022/10/11 18:42:39][INFO][百纳.flow][0] 流程 百纳.flow 开始运行
[2022/10/11 18:42:39][INFO][百纳.flow][0] 进入流程块“初始化配置”
[2022/10/11 18:42:39][INFO][流程块1.task][1] 进入初始化配置
[2022/10/11 18:42:46][INFO][百纳.flow][0] 进入流程块“导出储值消费表”
[2022/10/11 18:42:46][INFO][流程块2.task][8] 进入导出储值消费表
[2022/10/11 18:43:09][INFO][流程块2.task][49] {
	"File" : "流程块2.task",
	"Line" : 43,
	"Message" : "模块 UiElement.UiElementAuto.GetValue 命令出错：Exception has been thrown by the target of an invocation.\n元素未找到",
	"_InternalState_" : 1
}
[2022/10/11 18:43:22][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:43:22][INFO][百纳.flow][0] 判断“重试”结果为真(yes)
[2022/10/11 18:43:22][INFO][百纳.flow][0] 进入流程块“导出储值消费表”
[2022/10/11 18:43:22][INFO][流程块2.task][8] 进入导出储值消费表
[2022/10/11 18:43:45][INFO][流程块2.task][49] {
	"File" : "流程块2.task",
	"Line" : 43,
	"Message" : "模块 UiElement.UiElementAuto.GetValue 命令出错：Exception has been thrown by the target of an invocation.\n元素未找到",
	"_InternalState_" : 1
}
[2022/10/11 18:43:59][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:43:59][INFO][百纳.flow][0] 判断“重试”结果为真(yes)
[2022/10/11 18:43:59][INFO][百纳.flow][0] 进入流程块“导出储值消费表”
[2022/10/11 18:43:59][INFO][流程块2.task][8] 进入导出储值消费表
[2022/10/11 18:44:21][INFO][流程块2.task][49] {
	"File" : "流程块2.task",
	"Line" : 43,
	"Message" : "模块 UiElement.UiElementAuto.GetValue 命令出错：Exception has been thrown by the target of an invocation.\n元素未找到",
	"_InternalState_" : 1
}
[2022/10/11 18:45:16][INFO][流程块2.task][112] 离开导出储值消费表
[2022/10/11 18:45:16][INFO][百纳.flow][0] 进入流程块“储值表录入”
[2022/10/11 18:45:16][INFO][流程块.task][17] 进入储值表录入
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:45:26][INFO][流程块3.task][1] 进入异常处理
[2022/10/11 18:45:26][INFO][流程块3.task][3] 离开异常处理
[2022/10/11 18:45:26][INFO][百纳.flow][0] 判断“重试”结果为真(yes)
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“储值表录入”
[2022/10/11 18:45:26][INFO][流程块.task][17] 进入储值表录入
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:45:26][INFO][流程块3.task][1] 进入异常处理
[2022/10/11 18:45:26][INFO][流程块3.task][3] 离开异常处理
[2022/10/11 18:45:26][INFO][百纳.flow][0] 判断“重试”结果为真(yes)
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“储值表录入”
[2022/10/11 18:45:26][INFO][流程块.task][17] 进入储值表录入
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:45:26][INFO][流程块3.task][1] 进入异常处理
[2022/10/11 18:45:26][INFO][流程块3.task][3] 离开异常处理
[2022/10/11 18:45:26][INFO][百纳.flow][0] 判断“重试”结果为真(yes)
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“储值表录入”
[2022/10/11 18:45:26][INFO][流程块.task][17] 进入储值表录入
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:45:26][INFO][流程块3.task][1] 进入异常处理
[2022/10/11 18:45:26][INFO][流程块3.task][3] 离开异常处理
[2022/10/11 18:45:26][INFO][百纳.flow][0] 判断“重试”结果为真(yes)
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“储值表录入”
[2022/10/11 18:45:26][INFO][流程块.task][17] 进入储值表录入
[2022/10/11 18:45:26][INFO][百纳.flow][0] 进入流程块“异常处理”
[2022/10/11 18:45:26][INFO][流程块3.task][1] 进入异常处理
[2022/10/11 18:45:27][INFO][流程块3.task][3] 离开异常处理
[2022/10/11 18:45:27][INFO][百纳.flow][0] 判断“重试”结果为假(no)
[2022/10/11 18:45:27][INFO][百纳.flow][0] 百纳.flow 运行已结束
